apiVersion: v1
kind: ReplicationController
metadata:
  name: alligrader-api-deployment
spec:
  replicas: 1 
  selector:
      app: alligrader-api-deployment
  template: 
    metadata:
      labels:
          app: alligrader-api-deployment
    spec:
      containers:
      - name: frontend
        image: alligrader/gradebook-backend:latest
        ports:
        - containerPort: 80
