apiVersion: v1
kind: ReplicationController
metadata:
  name: alligrader-autograder-deployment
spec:
  replicas: 1 
  selector:
      app: alligrader-autograder-deployment
  template: 
    metadata:
      labels:
          app: alligrader-autograder-deployment
    spec:
      containers:
      - name: frontend
        image: alligrader/autograder:latest
        ports:
        - containerPort: 80
