apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: frontend-deployment

spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: alligrader-autograder
    spec:
        containers:
        - name: alligrader-autograder
          image: alligrader/autograder:latest
          ports:
          - containerPort: 80
