apiVersion: v1
kind: ReplicationController
metadata:
  name: alligrader-frontend-deployment
spec:
  replicas: 1 
  selector:
      app: alligrader-frontend-deployment
  template: 
    metadata:
      labels:
          app: alligrader-frontend-deployment
    spec:
      containers:
      - name: frontend
        image: alligrader/gradebook:latest
        ports:
        - containerPort: 8080
